// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  sidebar: [
    "introduction",
    {
      type: "category",
      label: "Quickstart",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "quickstart" }],
    },
    {
      type: "category",
      label: "SDKs Reference",
      items: [
        "sdks/playwright/index",
        "sdks/storybook/index",
        "sdks/cypress/index",
        "sdks/webdriverio/index",
        "sdks/puppeteer/index",
        "sdks/cli",
        "sdks/nodejs",
      ],
    },
    {
      type: "category",
      label: "Learn",
      items: [{ type: "autogenerated", dirName: "learn" }],
    },
  ],
};

module.exports = sidebars;
